### ISSUE TITLE
Default help command seem to crash the app 

### ISSUE THREAD

**Issue by DmitryGrayscale** [zekroTJA/shireikan#3]
Looks like it was introduced after di implementation:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x6e0537]

goroutine 70 [running]:
github.com/zekroTJA/shireikan.(*defaultHelpCommand).Exec(0xa1ea00, 0x822cc0, 0xc000178240, 0x822cc0, 0xc000178240)
	/home/grayscale/go/src/github.com/zekroTJA/shireikan/defaulthelp.go:53 +0x1b7
github.com/zekroTJA/shireikan.(*handler).messageHandler(0xc000178000, 0xc00007f880, 0xc000490dc0, 0x0)
	/home/grayscale/go/src/github.com/zekroTJA/shireikan/handler.go:351 +0x422
github.com/zekroTJA/shireikan.(*handler).Setup.func1(0xc00007f880, 0xc000482530)
	/home/grayscale/go/src/github.com/zekroTJA/shireikan/handler.go:207 +0x46
github.com/bwmarrin/discordgo.messageCreateEventHandler.Handle(0xc0002c8ef0, 0xc00007f880, 0x762740, 0xc000482530)
	/home/grayscale/go/src/github.com/bwmarrin/discordgo/eventhandlers.go:518 +0x4b
created by github.com/bwmarrin/discordgo.(*Session).handle
	/home/grayscale/go/src/github.com/bwmarrin/discordgo/event.go:171 +0x111
```

Seems like it is in https://github.com/zekroTJA/shireikan/blob/master/defaulthelp.go#L49
```go
	handler, _ := ctx.GetObject("cmdhandler").(Handler)
```
there is no "cmdhandler" object in objectContainer.
Adding the following helps, but will not work for custom objectContainers I guess (https://github.com/zekroTJA/shireikan/blob/master/examples/di/main.go)

```go
	if handler.objectContainer == nil {
		builder, _ := di.NewBuilder()
		builder.Set("cmdhandler", handler)

		handler.objectContainer = builder.Build()
	}
```

At least it should not lead to crash

**Comment by zekroTJA** [comment]
Oh yeah, I totally forgot about that when I made the last update. The changes ce9c111 should fix this, I guess.

Thank you really much. 😄

Edit: By the way, there is the constant `shireikan.ObjectMapKeyHandler` which contains the object map key for the command handler instance. You can use it so that you don't need to mind about the exact key value across your app. 😉
https://github.com/zekroTJA/shireikan/blob/e8b19094a3517219707237a24a695c21129b75e0/vars.go#L8
